#!/usr/bin/env bash
# SelectAI — diagnose & fix homepage routing on the server
# Run:  cd /var/www/SelectAI && sudo bash deploy/fix-homepage.sh

set -uo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  exec sudo bash "$0" "$@"
fi

APP_ROOT="/var/www/SelectAI"
NGINX_SITE="selectai"
NGINX_AVAILABLE="/etc/nginx/sites-available/${NGINX_SITE}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${NGINX_SITE}"
BACKUP_DIR="/etc/nginx/backup/$(date +%Y%m%d-%H%M%S)"

echo ""
echo "============================================================"
echo " SelectAI homepage fix (must run as root/sudo)"
echo "============================================================"
echo ""

echo "── 1. Static files ──"
for f in index.html login.html signin.html js/root-redirect.js; do
  if [[ -f "${APP_ROOT}/${f}" ]]; then
    echo "  OK  ${f}"
  else
    echo "  MISSING  ${f}"
  fi
done
echo ""

echo "── 2. FIND login.html redirect in nginx (this is the bug) ──"
LOGIN_HITS=$(grep -rn "login\.html\|signin\.html" /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/conf.d 2>/dev/null || true)
if [[ -n "$LOGIN_HITS" ]]; then
  echo "$LOGIN_HITS" | sed 's/^/  /'
else
  echo "  (no login.html references found in nginx config dirs)"
fi
echo ""

echo "── 3. All enabled nginx sites ──"
ls -la /etc/nginx/sites-enabled/ 2>/dev/null | sed 's/^/  /' || true
echo ""

echo "── 4. Before fix: what HTTPS / returns ──"
curl -skI -H "Host: www.selectai.it.com" https://127.0.0.1/ 2>/dev/null | head -10 | sed 's/^/  /' || true
echo ""

echo "── 5. Backup & disable conflicting site configs ──"
mkdir -p "$BACKUP_DIR"
shopt -s nullglob
for f in /etc/nginx/sites-enabled/*; do
  base=$(basename "$f")
  if [[ "$base" == "$NGINX_SITE" ]]; then
    continue
  fi
  if grep -q "login\.html\|signin\.html" "$f" 2>/dev/null || \
     grep -q "selectai" "$f" 2>/dev/null; then
    echo "  Disabling: $f"
    cp -a "$f" "${BACKUP_DIR}/"
    rm -f "$f"
  fi
done
shopt -u nullglob
echo "  Backups saved to: ${BACKUP_DIR}/"
echo ""

echo "── 6. Write new nginx config (index.html at /, NO login redirect) ──"

SSL_CERT=""
SSL_KEY=""
for dir in /etc/letsencrypt/live/www.selectai.it.com \
           /etc/letsencrypt/live/selectai.it.com; do
  if [[ -f "${dir}/fullchain.pem" && -f "${dir}/privkey.pem" ]]; then
    SSL_CERT="${dir}/fullchain.pem"
    SSL_KEY="${dir}/privkey.pem"
    break
  fi
done

if [[ -n "$SSL_CERT" ]]; then
  echo "  Using SSL cert: ${SSL_CERT}"
  cat > "${NGINX_AVAILABLE}" <<NGINX_SSL
# SelectAI — auto-generated by deploy/fix-homepage.sh
# Serves index.html at / (NOT login.html)

server {
    listen 80;
    listen [::]:80;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;
    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;

    root ${APP_ROOT};
    index index.html;

    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;

    ssl_certificate     ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = / {
        try_files /index.html =404;
    }

    # Clean URLs (no .html in address bar)
    location = /index.html  { return 301 /$is_args$args; }
    location = /login.html  { return 301 /welcome$is_args$args; }
    location = /signin.html { return 301 /sign-in$is_args$args; }
    location ~ ^/(.+)\.html$ { return 301 /$1$is_args$args; }

    location = /sign-in { try_files /signin.html =404; }
    location = /welcome { try_files /login.html =404; }

    location / {
        try_files \$uri \$uri.html \$uri/ =404;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_SSL
else
  echo "  No SSL cert found — writing HTTP-only config"
  cat > "${NGINX_AVAILABLE}" <<NGINX_HTTP
# SelectAI — auto-generated by deploy/fix-homepage.sh
server {
    listen 80;
    listen [::]:80;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;
    root ${APP_ROOT};
    index index.html;
    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;
    location = / { try_files /index.html =404; }
    location = /index.html  { return 301 /$is_args$args; }
    location = /login.html  { return 301 /welcome$is_args$args; }
    location = /signin.html { return 301 /sign-in$is_args$args; }
    location ~ ^/(.+)\.html$ { return 301 /$1$is_args$args; }
    location = /sign-in { try_files /signin.html =404; }
    location = /welcome { try_files /login.html =404; }
    location / { try_files \$uri \$uri.html \$uri/ =404; }
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_HTTP
fi

ln -sf "${NGINX_AVAILABLE}" "${NGINX_ENABLED}"
rm -f /etc/nginx/sites-enabled/default

# Neuter sites-available/default so re-enabling it cannot restore login redirect
if [[ -f /etc/nginx/sites-available/default ]]; then
  cp -a /etc/nginx/sites-available/default "${BACKUP_DIR}/default.sites-available" 2>/dev/null || true
  sed -i 's/index login\.html/index index.html/g' /etc/nginx/sites-available/default
  sed -i '/return 302 \/login\.html/d' /etc/nginx/sites-available/default
  sed -i 's/return 302 \/login\.html;//g' /etc/nginx/sites-available/default
fi

echo "  Config written: ${NGINX_AVAILABLE}"
echo "  Enabled: ${NGINX_ENABLED}"
ls -la /etc/nginx/sites-enabled/ | sed 's/^/    /'
echo ""

echo "── 7. Test & reload nginx ──"
nginx -t
systemctl daemon-reload 2>/dev/null || true
systemctl reload nginx
sleep 1
echo "  nginx reloaded OK"
echo ""

echo "── 8. After fix: what HTTPS / returns (expect 200, NOT 302 to login) ──"
HEADERS=""
for i in 1 2 3; do
  HEADERS=$(curl -skI -H "Host: www.selectai.it.com" https://127.0.0.1/ 2>/dev/null || true)
  if echo "$HEADERS" | grep -q "HTTP/.* 200"; then
    break
  fi
  sleep 1
done
echo "$HEADERS" | head -10 | sed 's/^/  /'

if echo "$HEADERS" | grep -qi "location:.*login\.html"; then
  echo ""
  echo "  *** STILL REDIRECTING TO login.html ***"
  echo "  Run manually:  sudo grep -rn login /etc/nginx/"
  exit 1
fi

BODY=$(curl -sk -H "Host: www.selectai.it.com" https://127.0.0.1/ 2>/dev/null | head -8 || true)
if echo "$BODY" | grep -qi "hero-title\|Welcome to SelectAI Innovations\|live-metrics"; then
  echo ""
  echo "  SUCCESS: homepage (index.html) is now served at /"
else
  echo ""
  echo "  Response body preview:"
  echo "$BODY" | sed 's/^/    /'
fi

echo ""
echo "Done. Test in browser (incognito): https://www.selectai.it.com"
echo "Watch hits:  sudo tail -f /var/log/nginx/selectai-access.log"
echo ""
