#!/usr/bin/env bash
# SelectAI — diagnose & fix homepage routing on the server
# Run:  cd /var/www/SelectAI && sudo bash deploy/fix-homepage.sh

set -uo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  exec sudo bash "$0" "$@"
fi

APP_ROOT="/var/www/SelectAI"
NGINX_SITE="selectai"
NGINX_AVAILABLE="/etc/nginx/sites-available/${NGINX_SITE}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${NGINX_SITE}"
BACKUP_DIR="/etc/nginx/backup/$(date +%Y%m%d-%H%M%S)"

write_nginx_config() {
  local ssl_cert="$1"
  local ssl_key="$2"
  local ssl_opts=""
  local ssl_dhparam=""
  [[ -f /etc/letsencrypt/options-ssl-nginx.conf ]] && ssl_opts="include /etc/letsencrypt/options-ssl-nginx.conf;"
  [[ -f /etc/letsencrypt/ssl-dhparams.pem ]] && ssl_dhparam="ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"

  if [[ -n "$ssl_cert" ]]; then
    cat > "${NGINX_AVAILABLE}" <<NGINX_EOF
# SelectAI — auto-generated by deploy/fix-homepage.sh
server {
    listen 80;
    listen [::]:80;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;
    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;

    root ${APP_ROOT};
    index index.html;

    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;

    ssl_certificate     ${ssl_cert};
    ssl_certificate_key ${ssl_key};
    ${ssl_opts}
    ${ssl_dhparam}

    location = / { try_files /index.html =404; }

    location = /index.html  { return 301 /\$is_args\$args; }
    location = /login.html  { return 301 /welcome\$is_args\$args; }
    location = /signin.html { return 301 /sign-in\$is_args\$args; }
    location ~ ^/(.+)\.html\$ { return 301 /\$1\$is_args\$args; }

    location = /sign-in { try_files /signin.html =404; }
    location = /welcome { try_files /login.html =404; }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        try_files \$uri \$uri.html \$uri/ =404;
    }
}
NGINX_EOF
  else
    cat > "${NGINX_AVAILABLE}" <<NGINX_EOF
# SelectAI — auto-generated by deploy/fix-homepage.sh (HTTP only)
server {
    listen 80;
    listen [::]:80;
    server_name selectai.com www.selectai.com selectai.it.com www.selectai.it.com;
    root ${APP_ROOT};
    index index.html;
    access_log /var/log/nginx/selectai-access.log;
    error_log  /var/log/nginx/selectai-error.log;

    location = / { try_files /index.html =404; }
    location = /index.html  { return 301 /\$is_args\$args; }
    location = /login.html  { return 301 /welcome\$is_args\$args; }
    location = /signin.html { return 301 /sign-in\$is_args\$args; }
    location ~ ^/(.+)\.html\$ { return 301 /\$1\$is_args\$args; }
    location = /sign-in { try_files /signin.html =404; }
    location = /welcome { try_files /login.html =404; }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / { try_files \$uri \$uri.html \$uri/ =404; }
}
NGINX_EOF
  fi
}

echo ""
echo "============================================================"
echo " SelectAI homepage fix (must run as root/sudo)"
echo "============================================================"
echo ""

echo "── 1. Static files ──"
for f in index.html login.html signin.html js/routes.js; do
  if [[ -f "${APP_ROOT}/${f}" ]]; then
    echo "  OK  ${f}"
  else
    echo "  MISSING  ${f}"
  fi
done
echo ""

echo "── 2. FIND login.html redirect in nginx ──"
grep -rn "login\.html\|signin\.html" /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/conf.d 2>/dev/null | sed 's/^/  /' \
  || echo "  (none — good)"
echo ""

echo "── 3. All enabled nginx sites ──"
ls -la /etc/nginx/sites-enabled/ 2>/dev/null | sed 's/^/  /' || true
echo ""

echo "── 4. Before fix: HTTPS / ──"
curl -skI -H "Host: www.selectai.it.com" https://127.0.0.1/ 2>/dev/null | head -6 | sed 's/^/  /' || echo "  (no response)"
echo ""

echo "── 5. Backup & disable conflicting configs ──"
mkdir -p "$BACKUP_DIR"
[[ -f "$NGINX_AVAILABLE" ]] && cp -a "$NGINX_AVAILABLE" "${BACKUP_DIR}/selectai.bak"
shopt -s nullglob
for f in /etc/nginx/sites-enabled/*; do
  base=$(basename "$f")
  [[ "$base" == "$NGINX_SITE" ]] && continue
  echo "  Disabling: $f"
  cp -a "$f" "${BACKUP_DIR}/" 2>/dev/null || true
  rm -f "$f"
done
shopt -u nullglob
echo "  Backups: ${BACKUP_DIR}/"
echo ""

echo "── 6. Write nginx config ──"
SSL_CERT=""
SSL_KEY=""
for dir in /etc/letsencrypt/live/www.selectai.it.com \
           /etc/letsencrypt/live/selectai.it.com; do
  if [[ -f "${dir}/fullchain.pem" && -f "${dir}/privkey.pem" ]]; then
    SSL_CERT="${dir}/fullchain.pem"
    SSL_KEY="${dir}/privkey.pem"
    break
  fi
done

if [[ -n "$SSL_CERT" ]]; then
  echo "  SSL cert: ${SSL_CERT}"
else
  echo "  No SSL cert — HTTP only"
fi

write_nginx_config "$SSL_CERT" "$SSL_KEY"

ln -sf "${NGINX_AVAILABLE}" "${NGINX_ENABLED}"
rm -f /etc/nginx/sites-enabled/default

if [[ -f /etc/nginx/sites-available/default ]]; then
  cp -a /etc/nginx/sites-available/default "${BACKUP_DIR}/default.sites-available" 2>/dev/null || true
  sed -i 's/index login\.html/index index.html/g' /etc/nginx/sites-available/default
  sed -i '/return 302 \/login\.html/d' /etc/nginx/sites-available/default
fi

echo "  Written: ${NGINX_AVAILABLE}"
echo ""

echo "── 7. Test & restart nginx ──"
if ! nginx -t 2>&1 | sed 's/^/  /'; then
  echo ""
  echo "  FATAL: nginx config invalid. Restoring backup..."
  [[ -f "${BACKUP_DIR}/selectai.bak" ]] && cp -a "${BACKUP_DIR}/selectai.bak" "${NGINX_AVAILABLE}"
  nginx -t && systemctl restart nginx || exit 1
  echo "  Restored previous config."
  exit 1
fi

systemctl restart nginx
sleep 2
systemctl is-active --quiet nginx && echo "  nginx: RUNNING" || { echo "  nginx: FAILED"; exit 1; }
echo ""

echo "── 8. Verify HTTPS / ──"
HEADERS=$(curl -skI -H "Host: www.selectai.it.com" https://127.0.0.1/ 2>/dev/null || true)
echo "$HEADERS" | head -8 | sed 's/^/  /'

if echo "$HEADERS" | grep -qi "location:.*login\.html"; then
  echo "  *** Still redirecting to login.html ***"
  exit 1
fi

if echo "$HEADERS" | grep -q "HTTP/.* 200"; then
  echo ""
  echo "  SUCCESS: homepage served at /"
else
  echo ""
  echo "  Unexpected response — check: sudo tail -20 /var/log/nginx/error.log"
fi

echo ""
echo "Done. Open https://www.selectai.it.com (incognito)"
echo "Logs: sudo tail -f /var/log/nginx/selectai-access.log"
echo ""
